baseURL = "https://changcui.cc/"
languageCode = "en-US"
title = "Chang Cui（崔唱）"
theme = "hugo-bearblog"

author = "Chang Cui（崔唱）"
copyright = "Chang Cui"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]

[params]
  description = "Chang Cui（崔唱） — Software Engineer, DevTech at NVIDIA."
  favicon = "favicon.png"
  title = "Chang Cui（崔唱）"
  hideMadeWithLine = true

[caches]
  [caches.images]
    dir = ":cacheDir/images"
